using ChengYuan.EntityFrameworkCore;

namespace ChengYuan.TenantManagement;

public sealed class TenantManagementDbContextDesignTimeFactory : ChengYuanSqliteDesignTimeDbContextFactory<TenantManagementDbContext>;
