using ChengYuan.EntityFrameworkCore;

namespace ChengYuan.PermissionManagement;

public sealed class PermissionManagementDbContextDesignTimeFactory : ChengYuanSqliteDesignTimeDbContextFactory<PermissionManagementDbContext>;
