version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    groups:
      xunit:
        patterns: ["xunit*"]
      testing-infra:
        patterns: ["coverlet*", "Microsoft.NET.Test.Sdk"]
    open-pull-requests-limit: 10
