using ChengYuan.EntityFrameworkCore;

namespace ChengYuan.BackgroundJobs;

public sealed class BackgroundJobDbContextDesignTimeFactory : ChengYuanSqliteDesignTimeDbContextFactory<BackgroundJobDbContext>;
