using ChengYuan.EntityFrameworkCore;

namespace ChengYuan.AuditLogging;

public sealed class AuditLoggingDbContextDesignTimeFactory : ChengYuanSqliteDesignTimeDbContextFactory<AuditLoggingDbContext>;
