using ChengYuan.EntityFrameworkCore;

namespace ChengYuan.FeatureManagement;

public sealed class FeatureManagementDbContextDesignTimeFactory : ChengYuanSqliteDesignTimeDbContextFactory<FeatureManagementDbContext>;
