using ChengYuan.EntityFrameworkCore;

namespace ChengYuan.SettingManagement;

public sealed class SettingManagementDbContextDesignTimeFactory : ChengYuanSqliteDesignTimeDbContextFactory<SettingManagementDbContext>;
